pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'boo', url: 'https://github.com/boojanashree-g/pipeline_test.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building the application...'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
            }
        }
    }
}
